### ISSUE TITLE
Implementation (there is a bug, possibly) & style comments

### ISSUE THREAD

**Issue by Suntrie** [wishyoudie/GitJet#1]
1. Хорошо бы, чтобы в случае возникновения ошибок (например, при передачу в программу некорректной ссылки, выборе файла некорректного формата),  не в лог ошибки сыпались, а прилетало уведомление пользователю (в идеале - блокировать кнопку). И по UI - пользователю, конечно, нужен бы какой-нибудь спиннер, который крутится, пока проходит искомый анализ
2. Utils -> killWindow - обычно killXXX это что-то сравнительно эсктренное и большое, вроде останова jvm и т.д. Здесь лучше просто close/finish
3. ReposHandler. ExecutorService executor = Executors.newFixedThreadPool(1); - насколько тогда эффективно создавать прямо экзекьютер? Почему бы не обойтись просто потоком? Можно ли разделять один экзекьютер несколькими обновлениями (например, для ситуации, когда руками вбиваются репозитории)? Я бы предложила Вам попробовать это сделать (для начала нужно попробовать найти/создать большие клонируемые репо), и замерить время (например, через System.currentTimeMillis())- получится ли на параллельной обработке репозиториев получить реальный выигрыш? (возможно, такой сценарий проще покрыть тестами, чем воспроизвести вручную) До какого числа потоков стоит наращивать пулл и почему (основная нагрузка - сетевое взаимодействие, плюс, очевидно, как-то будет связано с числом задач)?
Что сейчас будет происходить с порожденным потоком при завершении работы приложения?
4. CloneProjects. runCloning -> localPath - существует класс Path, поэтому объект класса File xxxPath, кажется, не стоит всё-таки называть
(LineSize -> iterateStrings - аналогично).
Кроме этого, с ходу не очень понятно, зачем Вы сразу создаёте и удаляете временную папку для репозитория
5. CloneProjects. "5" лучше вынести в виде именованной константы (например, в тело класса). В каком-нибудь Spring проекте, например, подобное значение вообще зачастую подбирается из конфига. Такое решение позволяет "5" менять не в 10 местах, а в единственном (и изменения пропагейтятся,  например, у Вас в текущем случае - в том числе, затронет вывод в лог). И, в принципе, например, в AnalyzePom она же встречается.
6. ReposHandler. handle. Если итоговый null расценивается в качестве корректного возврата без краша приложения, хорошо бы уведомить пользователя, что операция не была успешной.
7. CheckTests. Должны ли методы данного класса быть методами уровня объектов или статическими методами? (создание объекта - выполнение ряда действий + текст, который надо прочитать; если без этого можно обойтись, лучше обойтись)
8. Utils-> getFilesArray. throw new IllegalArgumentException(""); - из реальной жизни - так лучше не делать. В случае неочевидных кейсов это может существенно затруднить отладку программы
9. System.out.println("Tests size: " + result); - можно посмотреть на @Sl4j в ломбоке, логгеры позволяют получить некоторый объём дополнительной служебной информации + формат можно конфигурировать централизованно
10.LineSize -> iterateStrings. if (Objects.equals(fileExtension, "java") || Objects.equals(fileExtension, "kt")) { - я бы посмотрела на Set.of(...).contains() для того, чтобы уменьшить объём кода
11. LineSize. countStrings - кажется, здесь, как и для клонирования репозиториев, стоит посмотреть в сторону try-with-resources (и заодно проверить себя, вспомнив, какие плюсы его применение предлагает)
12. Логически кажется, что, если вы тесты выводите отдельно, то количество строчек в проекте = общее количество - тесты.
13. В плане проектирования UI общие поля для ввода ссылок и чисел обычно, конечно, не делают (это можно сейчас смело игнорировать)
14. AnalyzePom. Пока не вполне очевидно, зачем в getDefaultBranch нужен цикл для перебора элементов (вроде используете вы всё равно только результаты последней итерации)
15. AnalyzePom. String data = readUrl(url); - может ли теоретически readUrl вернуть больше 1024 символов? Что произойдёт с программой?
16. AnalyzePom. isMavenRepository. Кажется, если произошло исключение (при этом - ловить лучше конкретные классы исключений, объединенные по |, иначе вы не знаете, то ли это исключение, которое вы хотели так обрабатывать, или, например, код не очень хорошо отработал и его надо поправить), то ответ должен быть "unknown"
17. ReposHandler.     public List<Repo> calculateSummary(List<Repo> repos) { - создавать объекты со специальными "ключами" (репозитории со специальными именами) в принципе, наверное, можно. Но более чистым решением, кажется, было бы выделение интерфейса с двумя(?) реализациями: RepositoryEvaluation -> Repository, MeanRepository, тогда их можно, например, в calculateSummary смело в общий список засунуть
18. Удалось ли в целом протестировать работу с поиском именно Maven проектов? Сколько в среднем занимает такой поиск?
19. Caused by: java.lang.IllegalArgumentException: Couldn't open 'data.dat' file.
	at ru.spbstu.gitjet/gitjet.model.ReposHandler.readData(ReposHandler.java:43)
	at ru.spbstu.gitjet/gitjet.controller.TableController.initData(TableController.java:190)
	at ru.spbstu.gitjet/gitjet.controller.TableController.initialize(TableController.java:179)
	... 54 more - при попытке ручного сабмита происходит вот такая ошибка. Сориентируйте, пожалуйста, как её можно починить? (собственно, по-моему, там пока баг в логике)

**Comment by s1ckoleg** [comment]
@Suntrie 
18. Скорее всего ошибка появляется, потому что нет data.dat файла. Мы его добавили в репозиторий, теперь если сделать пулл, то должно работать (либо просто если создать его вручную в корне проекта). 
17. Да, сам поиск занимает несколько секунд, а клонирование уже побольше, в зависимости от репозитория.

**Comment by wishyoudie** [comment]
@Suntrie 
Всё исправили.
